name: Run Discord Selfbot

on:
  push  # Runs when you push code
  workflow_dispatch:  # Allows manual execution

jobs:
  run-selfbot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Use your required Node.js version

      - name: Install Dependencies
        run: npm install

      - name: Start Selfbot
        env:
          TOKEN: ${{ secrets.TOKEN }}  # Store your bot token in GitHub Secrets
        run: node bot.js  # Change to your bot file name

      - name: Keep Alive (6h max)
        run: sleep 21600  # Keeps the bot running for 6 hours
